DROP DATABASE IF EXISTS jd2;

CREATE DATABASE jd2;

USE jd2;

CREATE TABLE IF NOT EXISTS document (id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
description VARCHAR(255),
unique_number VARCHAR(45) NOT NULL UNIQUE,
deleted TINYINT NOT NULL DEFAULT 0);